### ISSUE TITLE
missing package scripts

### ISSUE THREAD

**Issue by morph027** [Gregy/znapzend-debian#1]
Nice to see other people picking up znapzend ;)

I noticed you are using plain debian control files. You should add some package scripts taking care of restarted and stopped services:

https://github.com/oetiker/znapzend/blob/master/packaging/checkinstall/postinstall-pak
https://github.com/oetiker/znapzend/blob/master/packaging/checkinstall/preremove-pak

**Comment by Gregy** [comment]
It seems very usefull :)

Regarding the service scripts: I am not sure what functionality would be added? You tried my package and the service wasn't started on install and stopped on uninstall? Keep in mind that znapzend will refuse to start unless some plans are defined.

**Comment by Gregy** [comment]
I will close this issue but if you have something more to say feel free :)
