### ISSUE TITLE
Build of 0.21 fails on buster

### ISSUE THREAD

**Issue by Phlogi** [Gregy/znapzend-debian#15]
```dpkg-deb: building package 'znapzend' in '../znapzend_0.20.0-1_amd64.deb'.
 dpkg-genbuildinfo
 dpkg-genchanges  >../znapzend_0.20.0-1_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build .
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
Now running lintian znapzend_0.20.0-1_amd64.changes ...
warning: the authors of lintian do not recommend running it with root privileges!
W: znapzend source: diff-contains-git-control-dir .git
E: znapzend source: missing-build-dependency-for-dh-addon autoreconf => dh-autoreconf | debhelper (>= 9.20160403~) | debhelper-compat
W: znapzend source: missing-debian-source-format
W: znapzend source: build-depends-on-obsolete-package build-depends: dh-systemd (>= 1.5) => use debhelper (>= 9.20160709)
W: znapzend source: hyphen-in-native-debian-changelog-version 0.20.0-1
W: znapzend: new-package-should-close-itp-bug
W: znapzend: embedded-javascript-library usr/lib/x86_64-linux-gnu/Mojolicious/resources/public/mojo/jquery/jquery.js please use libjs-jquery
Finished running lintian.```

**Comment by gabviv73** [comment]
Despect of teh warnings, build is succesfull here.
Only changed the version in debian/changelog.

**Comment by matveevandrey** [comment]
> Despect of teh warnings, build is succesfull here.
> Only changed the version in debian/changelog.

Do you mind to share current 0.21 deb package? Thanks

**Comment by rokkoyama** [comment]
@matveevandrey The build succeeds and has been tested on an active deb buster server thoroughly. The builds warnings are innocuous. See my [0.21 tag](https://github.com/rokkoyama/znapzend-debian/releases/tag/0.21.0) for a release deb. My fork is the origin of gregy's commit for the 0.21 update.

@Gregy you are welcome to roll up the 0.21 package into your repositiory, and apply a 0.21 release tag if you wish.

**Comment by Gregy** [comment]
New package uploaded. I have also pushed a new build script which makes creating new deb files a bit easier.
