### ISSUE TITLE
Tips to build for ubuntu 21.04

### ISSUE THREAD

**Issue by gabviv73** [Gregy/znapzend-debian#16]
* Remove the dependendency on dh-systemd. The package has been removed, and contained only docs files. It's a dummy package since Debian 9. See [MDEV-25583 dh-systemd needs to be removed as a build dependency on Ubuntu/Debian - Jira]  (https://jira.mariadb.org/browse/MDEV-25583)

* Add debhelper as a required package to be installed prior bulding and remove dh-sysytemd:
`  sudo apt install git devscripts  unzip build-essential debhelper`

**Comment by Gregy** [comment]
Thanks, fixed
